<a href="https://colab.research.google.com/github/akshats911/AI-project/blob/main/spamClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q kaggle

In [2]:
cd /root

/root


In [3]:
!mkdir -p ~/.kaggle
!cp kaggle/kaggle.json ~/.kaggle/
!ls ~/.kaggle

kaggle.json


In [4]:
!chmod 600 /root/.kaggle/kaggle.json

In [5]:
!kaggle datasets download uciml/sms-spam-collection-dataset

sms-spam-collection-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)


In [6]:
!unzip -q sms-spam-collection-dataset.zip -d SMSSpamCollection

replace SMSSpamCollection/spam.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n


In [7]:
import pandas as pd
messages = pd.read_csv("/root/SMSSpamCollection/spam.csv",encoding='ISO-8859-1')
messages.drop(["Unnamed: 2","Unnamed: 3",	"Unnamed: 4"], axis=1, inplace=True)
messages.head(10)

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
5  spam  FreeMsg Hey there darling it's been 3 week's n...
6   ham  Even my brother is not like to speak with me. ...
7   ham  As per your request 'Melle Melle (Oru Minnamin...
8  spam  WINNER!! As a valued network customer you have...
9  spam  Had your mobile 11 months or more? U R entitle...

In [8]:
import re
import nltk
nltk.download()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> all


       | 
       | Downloading package abc to /root/nltk_data...
       |   Package abc is already up-to-date!
       | Downloading package alpino to /root/nltk_data...
       |   Package alpino is already up-to-date!
       | Downloading package averaged_perceptron_tagger to
       |     /root/nltk_data...
       |   Package averaged_perceptron_tagger is already up-to-date!
       | Downloading package averaged_perceptron_tagger_ru to
       |     /root/nltk_data...
       |   Package averaged_perceptron_tagger_ru is already up-to-
       |       date!
       | Downloading package basque_grammars to /root/nltk_data...
       |   Package basque_grammars is already up-to-date!
       | Downloading package biocreative_ppi to /root/nltk_data...
       |   Package biocreative_ppi is already up-to-date!
       | Downloading package bllip_wsj_no_aux to /root/nltk_data...
       |   Package bllip_wsj_no_aux is already up-to-date!
       | Downloading package book_grammars to /root/nltk_data..


---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q


True

In [9]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
wl = WordNetLemmatizer()
ps = PorterStemmer()
corpus = []

In [10]:
for i in range(len(messages)):
  # print(messages['v2'][i])
  review = re.sub('[^a-zA-Z]', ' ', messages['v2'][i])
  review = review.lower()
  review = review.split()
  # print(i)
  # print(review)
  review = [wl.lemmatize(word) for word in review if word not in stopwords.words('english')]
  review = ' '.join(review)
  corpus.append(review)


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
# tv = TfidfVectorizer(max_features=3900)
cv = CountVectorizer(max_features=3900)
X = cv.fit_transform(corpus).toarray()

In [12]:
import pandas as pd
df = pd.DataFrame(data= X.A, columns=cv.get_feature_names())
df

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


aah  aathi  abi  ability  abiola  abj  able  absolutly  abt  abta  ...  \
0       0      0    0        0       0    0     0          0    0     0  ...   
1       0      0    0        0       0    0     0          0    0     0  ...   
2       0      0    0        0       0    0     0          0    0     0  ...   
3       0      0    0        0       0    0     0          0    0     0  ...   
4       0      0    0        0       0    0     0          0    0     0  ...   
...   ...    ...  ...      ...     ...  ...   ...        ...  ...   ...  ...   
5567    0      0    0        0       0    0     0          0    0     0  ...   
5568    0      0    0        0       0    0     0          0    0     0  ...   
5569    0      0    0        0       0    0     0          0    0     0  ...   
5570    0      0    0        0       0    0     0          0    0     0  ...   
5571    0      0    0        0       0    0     0          0    0     0  ...   

      zealand  zebra  zed  zero  zf  zhong  zindgi  zoe  zogtorius  zoom  
0           0      0    0     0   0      0       0    0          0     0  
1           0      0    0     0   0      0       0    0          0     0  
2           0      0    0     0   0      0       0    0          0     0  
3           0      0    0     0   0      0       0    0          0     0  
4           0      0    0     0   0      0       0    0          0     0  
...       ...    ...  ...   ...  ..    ...     ...  ...        ...   ...  
5567        0      0    0     0   0      0       0    0          0     0  
5568        0      0    0     0   0      0       0    0          0     0  
5569        0      0    0     0   0      0       0    0          0     0  
5570        0      0    0     0   0      0       0    0          0     0  
5571        0      0    0     0   0      0       0    0          0     0  

[5572 rows x 3900 columns]

In [13]:
y = pd.get_dummies(messages['v1'])
y = y.iloc[:,1].values

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [22]:
X_test[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [16]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [17]:
model = keras.Sequential([
  keras.layers.Dense(3900,activation="relu",use_bias=True, kernel_initializer=tf.keras.initializers.HeNormal()),
  keras.layers.Dense(130,activation="relu",use_bias=True, kernel_initializer=tf.keras.initializers.HeNormal()), 
  keras.layers.Dense(10,activation="relu",use_bias=True, kernel_initializer=tf.keras.initializers.HeNormal()),
  keras.layers.Dense(1,activation="sigmoid", kernel_initializer='uniform')
])

In [18]:
model.compile(optimizer="adam",
            loss="binary_crossentropy",
            metrics=["accuracy"]
)

In [23]:
model.fit(X_train, y_train, epochs =100)

Epoch 1/100
140/140 [==============================] - 2s 6ms/step - loss: 0.2346 - accuracy: 0.9170
Epoch 2/100
140/140 [==============================] - 1s 6ms/step - loss: 0.0240 - accuracy: 0.9915
Epoch 3/100
140/140 [==============================] - 1s 6ms/step - loss: 0.0042 - accuracy: 0.9987
Epoch 4/100
140/140 [==============================] - 1s 6ms/step - loss: 9.9645e-04 - accuracy: 0.9998
Epoch 5/100
140/140 [==============================] - 1s 6ms/step - loss: 2.4181e-04 - accuracy: 1.0000
Epoch 6/100
140/140 [==============================] - 1s 6ms/step - loss: 1.2743e-04 - accuracy: 1.0000
Epoch 7/100
140/140 [==============================] - 1s 6ms/step - loss: 8.2270e-05 - accuracy: 1.0000
Epoch 8/100
140/140 [==============================] - 1s 6ms/step - loss: 5.7648e-05 - accuracy: 1.0000
Epoch 9/100
140/140 [==============================] - 1s 6ms/step - loss: 4.2531e-05 - accuracy: 1.0000
Epoch 10/100
140/140 [==============================] - 1s 6ms/step

In [24]:
results = model.evaluate(X_test,y_test,batch_size=128)
print("test loss, test acc:", results)

9/9 [==============================] - 0s 5ms/step - loss: 0.2903 - accuracy: 0.9830
test loss, test acc: [0.2902930974960327, 0.9829596281051636]


In [34]:
y_test

array([0, 0, 0, ..., 0, 0, 0], dtype=uint8)

In [31]:
y_pred = model.predict(X_test[:10])
for y in y_pred:
  if y<0.5:
    print("ham")
  else:
    print("spam")

1/1 [==============================] - 0s 28ms/step
ham
ham
ham
ham
ham
ham
ham
ham
ham
spam


In [36]:
Y_pred = model.predict(X_test)
Y_pred = np.around(Y_pred)

35/35 [==============================] - 0s 2ms/step


In [38]:
Y_pred[8:12]

array([[0.],
       [1.],
       [0.],
       [0.]], dtype=float32)

In [39]:
from sklearn.metrics import confusion_matrix
conf_m = confusion_matrix(y_test,Y_pred)
conf_m

array([[949,   0],
       [ 19, 147]])

In [40]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,Y_pred)
acc

0.9829596412556054